export const WS_ALL_CONNECTION_START = 'WS_ALL_CONNECTION_START';
export const WS_ALL_CONNECTION_SUCCESS = 'WS_ALL_CONNECTION_SUCCESS';
export const WS_ALL_CONNECTION_ERROR = 'WS_ALL_CONNECTION_ERROR';
export const WS_ALL_CONNECTION_CLOSED = 'WS_ALL_CONNECTION_CLOSED';
export const WS_ALL_GET_MESSAGE = 'WS_ALL_GET_MESSAGE';
