export const NORMA_API = 'https://norma.nomoreparties.space/api'
export const LOGIN = 'auth/login'
export const REGISTER = 'auth/register'
export const FORGOT_PASSWORD = 'password-reset'
export const RESET_PASSWORD = 'password-reset/reset'